config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :articles

  

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true,
	length: { minimum: 5} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	

	def index
		@articles = Article.all
	end

	def new
		@article =  Article.new
	end
	
	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)
			if @article.save
				redirect_to @article
			else
				render 'new'
			end

	end

	def show
		@article = Article.find(params[:id])
	end


    private
	def article_params
		params.require(:article).permit(:title, :text)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<%= link_to 'New Blog' , new_article_path %>

<h1>Articles</h1>
<table>
	<tr>
		<td>Title</td>
		<td>Text</td>
	</tr>

<% @articles.each do |a| %>
<tr>
		<td><%= a.title %></td>
		<td><%= a.text%></td>
</tr>
<%end%>

</table>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f|%> 
 
<% if @article.errors.any? %>
 <h2><%= pluralize(@article.errors.count,"error")%> Prohibited this article from being saved</h2>
<ul>	
	<% @article.errors.full_messages.each do |msg|%>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>
 <p>
   <%= f.label :title %><br>
   <%= f.text_field :title%>
 </p>

<p>
  <%= f.label :text%><br>
  <%= f.text_area :text%>
</p>

<p>
  <%= f.submit%>
</p>

<%end%>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
	<strong>Title: </strong>
		<%= @article.title%>
</p>

<p>
	<strong>Text: </strong>
	<%= @article.text%>
</p>

<%= link_to 'Back', articles_path%>

app/views/layouts/_footer.html.erb
<div class="footer">
		<p>&copy; MyRecipes 2015</p>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
	<div class="container">
		<%= link_to "myRecipes", "", class: "btn btn-lg btn-success", id: "logo"%>	
		<div class="nav-item">
			<%= link_to "link 1","", class: "btn btn-default btn-warning"%>
		</div>
		<div class="nav-item">
			<%= link_to "link 2","",class: "btn btn-warning btn-default"%>
		</div>
		<div class="nav-item">
			<%= link_to "link 3","",class: "btn btn-warning btn-default"%>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Recipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation'%>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer'%>	
	</div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="center jumbotron">
	<h1>Welcome to MyRecipes App</h1>
	<h2>This is the Home page</h2>
	<%= link_to 'Sign up now!','',class: 'btn btn-lg btn-success'%>
</div>

<div class="row">
	<div class="col-lg-4">
		<h2 class="midrow">View Recipes as Guest User</h2>
		<h3 class="left"> Browse and view recipes as a guest and Sign up later</h3>
		<p><%= link_to 'Browse Recipe Listings','',class: 'btn btn-warning btn-lg'%></p>
	</div>
	<div class="col-lg-4">
		<h2 class="midrow">View Recipes as Guest User</h2>
		<h3 class="left"> Browse and view recipes as a guest and Sign up later</h3>
		<p><%= link_to 'Browse Recipe Listings','',class: 'btn btn-warning btn-lg'%></p>
	</div>
	<div class="col-lg-4">
		<h2 class="midrow">View Recipes as Guest User</h2>
		<h3 class="left"> Browse and view recipes as a guest and Sign up later</h3>
		<p><%= link_to 'Browse Recipe Listings','',class: 'btn btn-warning btn-lg'%></p>
	</div>
</div>

<%= link_to 'yuvi','/articles'%>